name: 'Python GitHub Action'
description: 'A reusable Python action.'
inputs:
  example_input:
    description: 'Example input to show how to use inputs.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
