name: 'Python GitHub Action'
description: 'A reusable Python action.'
inputs:
  example_input1:
    description: 'Example input to show how to use inputs.'
    required: true
  example_input2:
    description: 'Example input to show how to use inputs.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --example_input1="${{ inputs.example_input1 }}"
    - --example_input2="${{ inputs.example_input2 }}"
