name: 'Python GitHub Action'
description: 'A reusable Python action.'
inputs:
  identityFile:
    description: 'The OpenZiti identity file to use'
    required: true
  githubEvent:
    description: 'The GitHub event to process'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --identityFile="${{ inputs.identityFile }}"
    - --githubEvent="${{ inputs.githubEvent }}"
