name: Example Workflow Using My Python Action

on:
  push:
    branches:
      - main

jobs:
  run-my-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Custom Python Action
        uses: dovholuknf/mm-notification-action@main
        with:
          example_input: 'Hello from my workflow!'
