name: Example Workflow Using My Python Action

on:
  push:
    branches:
      - main

jobs:
  run-my-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Secure webhook call
        uses: dovholuknf/mm-notification-action@main
        with:
          identityFile: ${{ cat(example.id.json) }}
          githubEvent:  ${{ toJson(github.event) }}
          url: ${{ secrets.ZHOOK_URL }}
          eventName: ${{ github.event_name }}
          destChannel: "zssh"

