name: Example Workflow Using My Python Action

on:
  push:
    branches:
      - main

jobs:
  run-my-action:
    runs-on: ubuntu-latest

    steps:
      - name: Run Custom Python Action
        uses: dovholuknf/mm-notification-action@main
        if: ${{ env.ZHOOK_URL != null }}
        with:
          # Identity JSON containing key to access a Ziti network
          zitiId: ${{ secrets.ZITI_MATTERMOST_IDENTITY }}

          # URL to post the payload. Note that the `zitiId` must provide access to a service
          # intercepting `my-mattermost-ziti-server`
          webhookUrl: ${{ secrets.ZHOOK_URL }}

          eventJson: ${{ toJson(github.event) }}
          senderUsername: "GitHubZ"
          destChannel: "dev-notifications"
