name: Example Workflow Using My Python Action

on:
  push:
    branches:
      - main

jobs:
  run-my-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Secure webhook call
        uses: dovholuknf/mm-notification-action@main
        with:
          identityFile: ${{ secrets.ZITI_MATTERMOST_IDENTITY }}
          githubEvent:  ${{ toJson(github.event) }}
          url: ${{ secrets.ZHOOK_URL }}
          username: "GitHubZ"
          destChannel: "dev-notifications"
